def get_alignments():
    alignments = [
        'chaotic evil',
        'chaotic neutral',
        'chaotic good',

        'neutral evil',
        'neutral neutral',
        'neutral good',

        'lawful evil',
        'lawful neutral',
        'lawful good',
    ]
    return alignments

def get_attributes():
    attributes = [
        'charisma',
        'constitution',
        'dexterity',
        'intelligence',
        'luck',
        'perception',
        'strength',
        'will',
        'wisdom'
    ]
    return attributes

def get_basic_colors():
    colors = [
        'black',
        'white',
        'grey',
        'brown',
        'red',
        'orange',
        'yellow',
        'green',
        'blue',
        'indigo',
        'violet',
    ]
    return colors

def get_colors():
    colors = [
        'alice blue',
        'antique white',
        'aqua',
        'aquamarine',
        'azure',
        'beige',
        'bisque',
        'black',
        'blanched almond',
        'blue',
        'blue violet',
        'brown',
        'burly wood',
        'cadet blue',
        'chartreuse',
        'chocolate',
        'coral',
        'cornflower blue',
        'cornsilk',
        'crimson',
        'cyan',
        'dark blue',
        'dark cyan',
        'dark goldenrod',
        'dark gray',
        'dark green',
        'dark khaki',
        'dark magenta',
        'dark olive green',
        'dark orange',
        'dark orchid',
        'dark red',
        'dark salmon',
        'dark seagreen',
        'dark slate blue',
        'dark slate gray',
        'dark turquoise',
        'darkv iolet',
        'deep pink',
        'deep sky blue',
        'dim gray',
        'dim grey',
        'dodger blue',
        'fire brick',
        'floral white',
        'forest green',
        'fuchsia',
        'gainsboro',
        'ghost white',
        'gold',
        'goldenrod',
        'gray',
        'green',
        'green yellow',
        'honeydew',
        'hot pink',
        'indian red',
        'indigo',
        'ivory',
        'khaki',
        'lavender',
        'lavender blush',
        'lawn green',
        'lemon chiffon',
        'light blue',
        'light coral',
        'light cyan',
        'light goldenrod yellow',
        'light gray',
        'light green',
        'light pink',
        'light salmon',
        'light seagreen',
        'light sky blue',
        'light slate gray',
        'light steel blue',
        'light yellow',
        'lime',
        'linen',
        'magenta',
        'maroon',
        'medium aquamarine',
        'medium blue',
        'medium orchid',
        'medium purple',
        'medium seagreen',
        'medium slate blue',
        'medium spring green',
        'medium turquoise',
        'medium violet red',
        'midnight blue',
        'mint cream',
        'misty rose',
        'moccasin',
        'navajo white',
        'navy',
        'oldlace',
        'olive',
        'olive drab',
        'orange',
        'orange red',
        'orchid',
        'pale goldenrod',
        'pale green',
        'pale turquoise',
        'pale violetred',
        'papaya whip',
        'peachpuff',
        'peru',
        'pink',
        'plum',
        'powder blue',
        'purple',
        'red',
        'rosy brown',
        'royal blue',
        'saddle brown',
        'salmon',
        'sandy brown',
        'sea green',
        'sea shell',
        'sienna',
        'silver',
        'sky blue',
        'slate blue',
        'slate gray',
        'snow',
        'spring green',
        'steel blue',
        'tan',
        'teal',
        'thistle',
        'tomato',
        'turquoise',
        'violet',
        'wheat',
        'white',
        'white smoke',
        'yellow',
        'yellow green'
    ]
    return colors

def get_elements():
    elements = [
        'air',
        'earth',
        'fire',
        'water'
    ]
    return elements

def get_gems():
    gems = [
        'agate',
        'amethyst',
        'amber',
        'aquamarine',
        'bloodstone',
        "cat's eye",
        'coral',
        'diamond',
        'emerald',
        'garnet',
        'hematite',
        'jade',
        'jasper',
        'lapis lazuli',
        'moonstone',
        'obsidian',
        'onyx',
        'opal',
        'pearl',
        'peridot',
        'pyrite',
        'quartz',
        'ruby',
        'sapphire',
        'serpentine',
        'sunstone',
        "tiger's eye",
        'turquoise',
        'topex'
    ]
    return gems

def get_liquid_types():
    liquid_types = [
        'thick',
        'thin',
        'soapy',
        'oily',
        'translucent',
        'opaque',
        'aerated',
        'boiling',
        'luminous',
        'clearish',
        'cloudy',
        'sparkling',
        'effervescent',
        'metalic',
        'iridescent',
        'metalic',
        'flashing',
        'phasing',
        'gaseous',
        'congealed',
    ]
    return liquid_types


def get_metals():
    metals= [
        'aluminium',
        'brass',
        'bronze',
        'chromium',
        'cobalt',
        'copper',
        'gold',
        'iridium',
        'iron',
        'lead',
        'magnesium',
        'mercury',
        'nickle',
        'palladium',
        'platinum',
        'plutonium',
        'mercury',
        'rhodium',
        'silver',
        'sodium',
        'tin',
        'titanium',
        'zinc',
        'adamante',
        'mithril',
        'orichalcum'
    ]
    return metals

def get_personalities():
    personalities = [
        'adventurous',
        'affectionate',
        'agreeable',
        'agreeable',
        'angry',
        'anxious',
        'arrogant',
        'articulate',
        'aspiring',
        'authoritarian',
        'benevolent',
        'calm',
        'caring',
        'careless',
        'cheerful',
        'childish',
        'confident',
        'cowardly',
        'daring',
        'dignified',
        'dishonest',
        'gloomy',
        'greedy',
        'grouchy',
        'guilty',
        'hateful',
        'jealous',
        'melodramatic',
        'empathetic',
        'evil',
        'faithful',
        'humorous',
        'honest',
        'heroic',
        'helpful',
        'idealistic',
        'impatient',
        'lazy',
        'mysterious',
        'nervous',
        'optimistic',
        'philosophical',
        'pious',
        'racist',
        'selfish',
        'sexist',
        'sexy',
        'spontaneous',
        'stoic',
        'trustworthy',
        'unfriendly',
        'unhappy',
        'wicked'
    ]
    return personalities


def get_smells():
    smells = [
        'earthy',
        'foul',
        'gamy',
        'noxious',
        'rancid',
        'smokey',
        'skunky',
        'moldy',
        'sweet',
        'fruity',
        'burnt',
        'delightful',
        'disgusting',
        'divine',
        'fermented',
        'flowery',
        'fermented',
        'herbal',
        'lemony',
        'herbal',
        'malodorous',
        'nauseating',
        'mouth-watering',
        'malodorous',
        'musky',
        'oniony',
        'spoiled',
        'rubbery',
        'tantalizing',
        'vinegary',
        'metalic',
        'yeasty',
        'alcoholic',
        'alkaline',
        'alcoholic',
        'minty',
        'piney',
        'sulphuric',
        'mildewed',
        'fishy',
        'dank',
        'shitty',
    ]
    return smells


def get_stones():
    stones = [
        'alabaster',
        'basalt',
        'coal',
        'clay',
        'granite',
        'limestone',
        'marble',
        'sandstone',
        'soapstone',
        'slate'
    ]
    return stones

def get_stuff():
    stuff = [
        'blood',
        'shit',
        'paper'
    ]
    return stuff

def get_traits():
    traits = [
        'charismatic',
        'repulsive',
        'healthy',
        'unhealthy',
        'agile',
        'clumsy',
        'smart',
        'ignorant',
        'lucky',
        'unluchy',
        'perceptive',
        'confused',
        'strong',
        'sickly',
        'obedient',
        'wise',
        'foolish'
    ]
    return traits
